import Head from "next/head";
export default function Home() {
  return (
    <>
      <Head>
        <title>Twitter 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="font-bold text-3xl text-white">
        <h1>Twitter 2.0</h1>
      </main>
    </>
  );
}
